### ISSUE TITLE
【机场签到相关】请求兼容通过formData方式传递账号密码的机场

### ISSUE THREAD

**Issue by Wo1framalpha** [evilbutcher/Quantumult_X#12]
我使用的机场今天不再通过url传递账号密码，改用formData方式了（仍然是明文），麻烦大佬兼容一下这种情况

一些登陆信息，希望能有所帮助：
![Snipaste_2020-11-11_10-36-53](https://user-images.githubusercontent.com/37956663/98758685-59cfde00-240a-11eb-9790-25ec568d7d57.png)

![Snipaste_2020-11-11_10-38-38](https://user-images.githubusercontent.com/37956663/98758696-60f6ec00-240a-11eb-82c1-7dd9b7e7460d.png)

![Snipaste_2020-11-11_10-39-24](https://user-images.githubusercontent.com/37956663/98758728-71a76200-240a-11eb-9cb5-89d308a52bd6.png)
![Snipaste_2020-11-11_10-40-14](https://user-images.githubusercontent.com/37956663/98758795-8f74c700-240a-11eb-8fe1-a2f7f49cc73f.png)

**Comment by evilbutcher** [comment]
这个我没太明白，是怎么找到的这个？

**Comment by Wo1framalpha** [comment]
> 这个我没太明白，是怎么找到的这个？

用F12抓登陆时发送的包抓到的

**Comment by evilbutcher** [comment]
> > 这个我没太明白，是怎么找到的这个？
> 
> 用F12抓登陆时发送的包抓到的

emmmm和脚本应该没有关系吧，如果和网站的通讯就是采用的明文，脚本应该也没法加密吧

**Comment by Wo1framalpha** [comment]
我看脚本的登陆方法是通过url传递账户和密码的，但我用的这个机场前几天改成用formData传递账户和密码了，继续使用脚本签到只会报错401
![Snipaste_2020-11-13_11-00-10](https://user-images.githubusercontent.com/37956663/99023549-c7614300-259f-11eb-90ec-30937ac096ca.png)

**Comment by evilbutcher** [comment]
> 我看脚本的登陆方法是通过url传递账户和密码的，但我用的这个机场前几天改成用formData传递账户和密码了，继续使用脚本签到只会报错401
> ![Snipaste_2020-11-13_11-00-10](https://user-images.githubusercontent.com/37956663/99023549-c7614300-259f-11eb-90ec-30937ac096ca.png)
> 

哦哦，我理解你的意思了，这种情况我有空看看吧，不过我感觉大概率不能用了😂

**Comment by Wo1framalpha** [comment]
我对前端其实一窍不通

> > 我看脚本的登陆方法是通过url传递账户和密码的，但我用的这个机场前几天改成用formData传递账户和密码了，继续使用脚本签到只会报错401
> > ![Snipaste_2020-11-13_11-00-10](https://user-images.githubusercontent.com/37956663/99023549-c7614300-259f-11eb-90ec-30937ac096ca.png)
> 
> 哦哦，我理解你的意思了，这种情况我有空看看吧，不过我感觉大概率不能用了😂

没法兼容的话也能用cookie版顶着，只是不如账户密码版一劳永逸，还得一月一续😂

**Comment by caork** [comment]
貌似登录问题可以解决，
![responce](https://user-images.githubusercontent.com/34786132/100303150-dcde6000-2fd6-11eb-9712-f06fed3af6d1.png)
![cordcloudlogin](https://user-images.githubusercontent.com/34786132/100303152-dea82380-2fd6-11eb-8255-e94fffc32c00.jpeg)
不过貌似签到也改了？ 我还在看

**Comment by evilbutcher** [comment]
> 貌似登录问题可以解决，
> ![responce](https://user-images.githubusercontent.com/34786132/100303150-dcde6000-2fd6-11eb-9712-f06fed3af6d1.png)
> ![cordcloudlogin](https://user-images.githubusercontent.com/34786132/100303152-dea82380-2fd6-11eb-8255-e94fffc32c00.jpeg)
> 不过貌似签到也改了？ 我还在看
> 

最近很忙，没有改过代码😂

**Comment by caork** [comment]
> > 貌似登录问题可以解决，
> > ![responce](https://user-images.githubusercontent.com/34786132/100303150-dcde6000-2fd6-11eb-9712-f06fed3af6d1.png)
> > ![cordcloudlogin](https://user-images.githubusercontent.com/34786132/100303152-dea82380-2fd6-11eb-8255-e94fffc32c00.jpeg)
> > 不过貌似签到也改了？ 我还在看
> 
> 最近很忙，没有改过代码

没，是cord他都改了，害 ，我再看看签到问题，搞完签到，应该就可以继续用了

**Comment by Wo1framalpha** [comment]
CordCloud用户可以fork[我的仓库](https://github.com/Wo1framalpha/CordCloud-Check-in)，配置Github Actions自动签到

https://github.com/Wo1framalpha/CordCloud-Check-in
