### ISSUE TITLE
NASA的问题

### ISSUE THREAD

**Issue by MW8023** [evilbutcher/Quantumult_X#2]
大佬 NASA的脚本报错了  返回信息是code：-1，我之前用的还好好的  我API也是正确的，也更新了脚本还有boxjs

**Comment by MW8023** [comment]
刚才还报code：-1的错误  现在又是暂无图片 我想应该可以了  没什么错误问题

**Comment by evilbutcher** [comment]
因为8:00-12:00，NASA接口还没把新图片加上去，所以会报错，等等就好了
