### ISSUE TITLE
✈AC签到是否还在后续更新

### ISSUE THREAD

**Issue by Saver233** [evilbutcher/Quantumult_X#23]
您好，麻烦问一下：您编写的签到是否还后续更新，日志出现错误。 [https://github.com/Saver233/airport_kejibear_action/runs/1712648810?check_suite_focus=true#step:5:37](url)

**Comment by evilbutcher** [comment]
我已经取消Action的支持了

**Comment by Saver233** [comment]
> 我已经取消Action的支持了

好的，谢谢
