### ISSUE TITLE
华住会签到异常

### ISSUE THREAD

**Issue by lioY3** [evilbutcher/Quantumult_X#27]
![image](https://user-images.githubusercontent.com/67148897/128540305-c4c7e75b-a06c-4903-9361-8390826584b8.jpeg)
![image](https://user-images.githubusercontent.com/67148897/128540367-988884c0-f0f7-4d42-9a6b-b7d931451724.jpeg)

**Comment by chuisoo1** [comment]
同问，华住ck获取不到

**Comment by lioY3** [comment]
华住会签到异常
![IMG_2612](https://user-images.githubusercontent.com/67148897/144034559-3ca18c0a-8f44-4224-97b4-1e81fe592325.PNG)
