### ISSUE TITLE
Quantumult_X运行失败无结果

### ISSUE THREAD

**Issue by mapeili521** [evilbutcher/Quantumult_X#28]
状态:		已释放
网络请求:	1
描述:		无
日志:		 	
❚  [Wechatsubs] LOG: READ wechatkeyword1
❚  [Wechatsubs] LOG: READ wechatkeyword1
❚  [Wechatsubs] LOG: READ wechatkeyword1
❚  [Wechatsubs] LOG: READ wechatkeyword2
❚  [Wechatsubs] LOG: READ wechatkeyword2
❚  [Wechatsubs] LOG: READ wechatkeyword2
❚  [Wechatsubs] LOG: READ wechatsavedtime
❚  [Wechatsubs] LOG: READ wechatsavedtime
❚  [Wechatsubs] LOG: SET wechatsavedtime
❚  [Wechatsubs] LOG: SET wechatsaveditem
❚  [Wechatsubs] LOG: READ wechatrefreshtime
❚  [Wechatsubs] LOG: READ wechatsaveditem
❚  [Wechatsubs] LOG: READ wechatsaveditem
❚  [Wechatsubs] LOG: READ wechatsaveditem
❚  [Wechatsubs] INFO: 关键词：IOS口袋和今日份iOS限时免费来啦！
❚  [Wechatsubs] LOG: {
  "url": "https://wx.sogou.com/weixin?type=2&query=IOS%E5%8F%A3%E8%A2%8B+%E4%BB%8A%E6%97%A5%E4%BB%BDiOS%E9%99%90%E6%97%B6%E5%85%8D%E8%B4%B9%E6%9D%A5%E5%95%A6%EF%BC%81",
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Connection": "keep-alive",
    "Referer": "https://wx.sogou.com/",
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "wx.sogou.com",
    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1",
    "Accept-Language": "zh-cn"
  }
}
❚  [Wechatsubs] INFO:
❚  [Wechatsubs] LOG:
❚  [Wechatsubs] LOG: https://wx.sogou.com/
❚  [Wechatsubs] LOG: SET wechatsaveditem

以上是JS运行日志记录
BoxJs里面我也设置好了，关键词和刷新时间，是哪里不对吗？

**Comment by evilbutcher** [comment]
现在还有这个问题吗？不好意思才看到…

**Comment by mapeili521** [comment]
一直没有搞懂，就放弃使用了，我现在看看能不能成功> 现在还有这个问题吗？不好意思才看到…
