### ISSUE TITLE
签到脚本可以支持一下Github action吗

### ISSUE THREAD

**Issue by LuzMasonj** [evilbutcher/Quantumult_X#3]
大佬你好，隔壁sazs34大佬用了一个smartreplace.js把京东脚本都放在了github上跑，感觉机场签到脚本也挺适合放在github上跑的，有机会支持一下嘛？
[sazs34/MyActions](https://github.com/sazs34/MyActions)

**Comment by evilbutcher** [comment]
等我有空看看搞一下

**Comment by LuzMasonj** [comment]
> 等我有空看看搞一下

麻烦了老哥

**Comment by LuzMasonj** [comment]
`https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js `
这个机场签到没有cookie失效的问题，非常适合

**Comment by evilbutcher** [comment]
> `https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js `
> 这个机场签到没有cookie失效的问题，非常适合

嗯嗯我想到的也是这个，等我有空看看把不需要cookie的都支持一下

**Comment by LuzMasonj** [comment]
> > `https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js `
> > 这个机场签到没有cookie失效的问题，非常适合
> 
> 嗯嗯我想到的也是这个，等我有空看看把不需要cookie的都支持一下

非常感谢 隔壁的一堆京东脚本共用一个cookie，失效后值得手动更换，机场签到的cookie就不太适合手动替换了。

**Comment by evilbutcher** [comment]
> > > `https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js `
> > > 这个机场签到没有cookie失效的问题，非常适合
> > 
> > 
> > 嗯嗯我想到的也是这个，等我有空看看把不需要cookie的都支持一下
> 
> 非常感谢 隔壁的一堆京东脚本共用一个cookie，失效后值得手动更换，机场签到的cookie就不太适合手动替换了。

已支持GitHub Action，Secrets中添加 CHECKIN_TITLE CHECKIN_URL CHECKIN_EMAIL CHECKIN_PASSWORD 四个数据，不同的账号以&分隔，定时和star均可运行

**Comment by LuzMasonj** [comment]
> > > > `https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js `
> > > > 这个机场签到没有cookie失效的问题，非常适合
> > > 
> > > 
> > > 嗯嗯我想到的也是这个，等我有空看看把不需要cookie的都支持一下
> > 
> > 非常感谢 隔壁的一堆京东脚本共用一个cookie，失效后值得手动更换，机场签到的cookie就不太适合手动替换了。
> 
> 已支持GitHub Action，Secrets中添加 CHECKIN_TITLE CHECKIN_URL CHECKIN_EMAIL CHECKIN_PASSWORD 四个数据，不同的账号以&分隔，定时和star均可运行

老哥牛逼

**Comment by LuzMasonj** [comment]
建议新开一个项目 可以减少pull request的频率

**Comment by evilbutcher** [comment]
> 建议新开一个项目 可以减少pull request的频率

可以用pull保持更新，不用自己操作的😂

**Comment by LuzMasonj** [comment]
> > 建议新开一个项目 可以减少pull request的频率
> 
> 可以用pull保持更新，不用自己操作的😂

也对 反正

> > 建议新开一个项目 可以减少pull request的频率
> 
> 可以用pull保持更新，不用自己操作的😂

也对 我这边也不需要修改代码 用pull覆盖就行
