### ISSUE TITLE
大佬。有一个小小的问题。

### ISSUE THREAD

**Issue by kk20180123** [evilbutcher/Quantumult_X#30]
麻烦问一下，app监控那个脚本我想把版本号去掉，怎么操作，删除哪块，求大佬指教。

**Comment by evilbutcher** [comment]
![image](https://user-images.githubusercontent.com/62224738/159679390-ee8bad01-8195-48cb-97d6-8bccb6185214.jpeg)才看到…你可以把我标注的删掉试试

**Comment by kk20180123** [comment]
> ![image](https://user-images.githubusercontent.com/62224738/159679390-ee8bad01-8195-48cb-97d6-8bccb6185214.jpeg)才看到…你可以把我标注的删掉试试

谢谢。
