### ISSUE TITLE
glados机场签到脚本问题

### ISSUE THREAD

**Issue by unishare2008** [evilbutcher/Quantumult_X#35]
您好，我想问一下glados签到的问题，我按您的说明文档配置了，但还是不行，不知道哪里出问题了，希望您能抽空帮忙看看，十分感谢！（证书都按要求添加了）
![IMAGE 2022-08-25 13:51:45](https://user-images.githubusercontent.com/844969/186585589-bc42cf04-5090-4c66-b9f7-4b4971b91ab9.jpg)
![IMAGE 2022-08-25 13:51:46](https://user-images.githubusercontent.com/844969/186585643-f4f60a59-b13c-442d-bc05-e248a7508215.jpg)
![IMAGE 2022-08-25 13:51:48](https://user-images.githubusercontent.com/844969/186585666-e702626b-c55e-493d-b3fc-4aacba941dce.jpg)

**Comment by evilbutcher** [comment]
已经修复了
