### ISSUE TITLE
微博超话签到失效

### ISSUE THREAD

**Issue by TychoSuen** [evilbutcher/Quantumult_X#40]
微博版本更新，原本我的-关注界面无法打开，旧版本这个界面也提示错误

**Comment by TychoSuen** [comment]
希望作者能抽空看一看

**Comment by qhy5697062** [comment]
我也遇到相同情况了

**Comment by qhy5697062** [comment]
> 微博版本更新，原本我的-关注界面无法打开，旧版本这个界面也提示错误

https://wb.dsttl3.cn/app/iOS.html
可以用这个快捷指令进行微博超话签到，很方便哈

**Comment by TychoSuen** [comment]
> > 微博版本更新，原本我的-关注界面无法打开，旧版本这个界面也提示错误
> 
> https://wb.dsttl3.cn/app/iOS.html 可以用这个快捷指令进行微博超话签到，很方便哈

好的👌

**Comment by shuiqingtian** [comment]
盼望更新

**Comment by fengyuan2333** [comment]
盼望更新+1

**Comment by evilbutcher** [comment]
已经黑号了，没法测试了，弃更
