### ISSUE TITLE
关于华住会相关代码的错误反馈

### ISSUE THREAD

**Issue by Yyzq12** [evilbutcher/Quantumult_X#44]
作者大佬您好！
我是一名使用您提供的华住会签到脚本的用户。我在运行代码的过程中遇到了一些问题，希望能向您反馈并寻求帮助。

当我执行脚本时，出现了如下错误信息提示：“解析数据出现问题，签到错误，请检查日志”
错误原因是Cookie和token值对应不上，当我再次手动签到尝试从新自动获取token值的时候，脚本没有像我第一次使用时那样自动获取，并发出弹窗提示获取cookie成功。

我也曾尝试手动抓取 Cookie 等步骤。但在后续运行中仍然遇到了这个错误。我不太确定问题出在哪里，是我的操作有误，还是代码在某些情况下存在兼容性问题或者其他潜在的缺陷。

我非常希望能够继续顺利使用您的脚本，并且很感谢您的分享。如果您能抽出时间帮我分析一下这个问题，或者给予一些解决问题的建议和指导，我将不胜感激。

再次感谢您的关注和支持！

祝您一切顺利！

**Comment by evilbutcher** [comment]
看另一个项目的PR吧，再试试
