### ISSUE TITLE
action运行机场签到提示错误! 

### ISSUE THREAD

**Issue by LuzMasonj** [evilbutcher/Quantumult_X#6]
❗️机场签到, 错误!
Error: Cookie not in this host's domain. Cookie:xiaoxiaobujidao.org Request:null
详细日志在附件，大佬抽空看看吧。
[logs_1.zip](https://github.com/evilbutcher/Quantumult_X/files/5232018/logs_1.zip)

**Comment by evilbutcher** [comment]
这个我看到了，在问大佬lol

**Comment by LuzMasonj** [comment]
> 这个我看到了，在问大佬lol

老哥现在还是提示错误呀 查到原因了嘛

**Comment by evilbutcher** [comment]
> > 这个我看到了，在问大佬lol
> 
> 老哥现在还是提示错误呀 查到原因了嘛

虽然有错误但不影响运行，可能是API的问题，C神暂时没空，先等等吧

**Comment by LuzMasonj** [comment]
好的老哥

**Comment by LuzMasonj** [comment]
希望大佬去我的GitHub里看看 签到报错好几天了
https://github.com/MisterGlasses/Quantumult_X/actions

**Comment by evilbutcher** [comment]
> 希望大佬去我的GitHub里看看 签到报错好几天了
> https://github.com/MisterGlasses/Quantumult_X/actions

最近修好了Quantumult X，这个又出问题了，一直没找到原因

**Comment by LuzMasonj** [comment]
> > 希望大佬去我的GitHub里看看 签到报错好几天了
> > https://github.com/MisterGlasses/Quantumult_X/actions
> 
> 最近修好了Quantumult X，这个又出问题了，一直没找到原因

大佬抽空查 不急的

**Comment by evilbutcher** [comment]
额，我决定取消对Action的支持了= =所以这个issue就先关啦

**Comment by LuzMasonj** [comment]
好的
